language: erlang
otp_release:
  - 19.2
  - 19.0
script: ./pest.erl -c ./pest.erl
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    on_success: change
    on_failure: always
